/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ShareSample } from "./ShareSample";
export * as factories from "./factories";
export { ShareSample__factory } from "./factories/ShareSample__factory";
