/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ShareSampleFactoryInterface extends utils.Interface {
  functions: {
    "createShareSample(address)": FunctionFragment;
    "deployedSubjects(uint256)": FunctionFragment;
    "getContractForSharesSubject(address)": FunctionFragment;
    "getDeployedContracts()": FunctionFragment;
    "newShareSample()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "subjectToContract(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createShareSample"
      | "deployedSubjects"
      | "getContractForSharesSubject"
      | "getDeployedContracts"
      | "newShareSample"
      | "owner"
      | "renounceOwnership"
      | "subjectToContract"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createShareSample",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedSubjects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractForSharesSubject",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newShareSample",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subjectToContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createShareSample",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedSubjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractForSharesSubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newShareSample",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subjectToContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "ShareSampleCreated(address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ShareSampleCreated"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ShareSampleCreatedEventObject {
  shareSampleAddress: string;
  subRate: BigNumber;
  sharesSubject: string;
}
export type ShareSampleCreatedEvent = TypedEvent<
  [string, BigNumber, string],
  ShareSampleCreatedEventObject
>;

export type ShareSampleCreatedEventFilter =
  TypedEventFilter<ShareSampleCreatedEvent>;

export interface ShareSampleFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShareSampleFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createShareSample(
      _sharesSubject: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    deployedSubjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getContractForSharesSubject(
      _sharesSubject: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getDeployedContracts(
      overrides?: CallOverrides
    ): Promise<[string[], string[]]>;

    newShareSample(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    subjectToContract(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  createShareSample(
    _sharesSubject: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  deployedSubjects(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getContractForSharesSubject(
    _sharesSubject: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getDeployedContracts(
    overrides?: CallOverrides
  ): Promise<[string[], string[]]>;

  newShareSample(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  subjectToContract(arg0: string, overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    createShareSample(
      _sharesSubject: string,
      overrides?: CallOverrides
    ): Promise<string>;

    deployedSubjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getContractForSharesSubject(
      _sharesSubject: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getDeployedContracts(
      overrides?: CallOverrides
    ): Promise<[string[], string[]]>;

    newShareSample(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    subjectToContract(arg0: string, overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "ShareSampleCreated(address,uint256,address)"(
      shareSampleAddress?: string | null,
      subRate?: BigNumberish | null,
      sharesSubject?: string | null
    ): ShareSampleCreatedEventFilter;
    ShareSampleCreated(
      shareSampleAddress?: string | null,
      subRate?: BigNumberish | null,
      sharesSubject?: string | null
    ): ShareSampleCreatedEventFilter;
  };

  estimateGas: {
    createShareSample(
      _sharesSubject: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    deployedSubjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContractForSharesSubject(
      _sharesSubject: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDeployedContracts(overrides?: CallOverrides): Promise<BigNumber>;

    newShareSample(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    subjectToContract(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createShareSample(
      _sharesSubject: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    deployedSubjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContractForSharesSubject(
      _sharesSubject: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeployedContracts(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newShareSample(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    subjectToContract(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
